name: "Wakumo AI Minimal Action"
description: "Minimal action: when @wakumo-ai is mentioned, create a conversation and comment the link."
branding:
  icon: "at-sign"
  color: "orange"

inputs:
  WKM_API_KEY:
    description: "Wakumo AI API Key"
    required: true
  WKM_API_URL:
    description: "(Optional) Wakumo AI API URL override."
    required: false
  system_prompt:
    description: "(Optional) Override the entire prompt sent to Wakumo AI."
    required: false
  append_system_prompt:
    description: "(Optional) Append additional instructions to the default prompt."
    required: false

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        bun install
    - name: Run Wakumo AI Action
      shell: bash
      run: bun run ${GITHUB_ACTION_PATH}/src/entrypoints/index.ts
      env:
        WKM_API_KEY: ${{ inputs.WKM_API_KEY }}
        WAKUMO_API_URL: ${{ inputs.WKM_API_URL }}
        SYSTEM_PROMPT: ${{ inputs.system_prompt }}
        APPEND_SYSTEM_PROMPT: ${{ inputs.append_system_prompt }}
        GITHUB_TOKEN: ${{ github.token }}
