name: Wakumo AI Code

description: Example workflow for triggering Wakumo AI Action on issues, comments, and reviews.

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  wakumo:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@wakumo-ai')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@wakumo-ai')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@wakumo-ai')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@wakumo-ai') || contains(github.event.issue.title, '@wakumo-ai')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run WakumoAI Action Code
        id: wakumo-ai
        uses: wakumo/wakumo-ai-action@beta
        with:
          WKM_API_KEY: ${{ secrets.WKM_API_KEY }}
          # Optional: override the Wakumo AI API endpoint (e.g. for staging or self-hosted)
          # WKM_API_URL: "https://api.staging.wakumo.ai"